#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require '/var/www/html/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once '/var/www/html/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
