/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthUsersRouteImport } from './routes/_auth.users'
import { Route as AuthSourcesRouteImport } from './routes/_auth.sources'
import { Route as AuthRepositoriesRouteImport } from './routes/_auth.repositories'
import { Route as AuthPersonalTokensRouteImport } from './routes/_auth.personal-tokens'
import { Route as AuthImportBatchesRouteImport } from './routes/_auth.import-batches'
import { Route as AuthDeployTokensRouteImport } from './routes/_auth.deploy-tokens'
import { Route as AuthAuthenticationSourcesRouteImport } from './routes/_auth.authentication-sources'
import { Route as AuthPackagesIndexRouteImport } from './routes/_auth.packages.index'
import { Route as AuthPackagesPackageIdRouteImport } from './routes/_auth.packages.$packageId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSourcesRoute = AuthSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRepositoriesRoute = AuthRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPersonalTokensRoute = AuthPersonalTokensRouteImport.update({
  id: '/personal-tokens',
  path: '/personal-tokens',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImportBatchesRoute = AuthImportBatchesRouteImport.update({
  id: '/import-batches',
  path: '/import-batches',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDeployTokensRoute = AuthDeployTokensRouteImport.update({
  id: '/deploy-tokens',
  path: '/deploy-tokens',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthenticationSourcesRoute =
  AuthAuthenticationSourcesRouteImport.update({
    id: '/authentication-sources',
    path: '/authentication-sources',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthPackagesIndexRoute = AuthPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPackagesPackageIdRoute = AuthPackagesPackageIdRouteImport.update({
  id: '/packages/$packageId',
  path: '/packages/$packageId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/authentication-sources': typeof AuthAuthenticationSourcesRoute
  '/deploy-tokens': typeof AuthDeployTokensRoute
  '/import-batches': typeof AuthImportBatchesRoute
  '/personal-tokens': typeof AuthPersonalTokensRoute
  '/repositories': typeof AuthRepositoriesRoute
  '/sources': typeof AuthSourcesRoute
  '/users': typeof AuthUsersRoute
  '/': typeof AuthIndexRoute
  '/packages/$packageId': typeof AuthPackagesPackageIdRoute
  '/packages': typeof AuthPackagesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/authentication-sources': typeof AuthAuthenticationSourcesRoute
  '/deploy-tokens': typeof AuthDeployTokensRoute
  '/import-batches': typeof AuthImportBatchesRoute
  '/personal-tokens': typeof AuthPersonalTokensRoute
  '/repositories': typeof AuthRepositoriesRoute
  '/sources': typeof AuthSourcesRoute
  '/users': typeof AuthUsersRoute
  '/': typeof AuthIndexRoute
  '/packages/$packageId': typeof AuthPackagesPackageIdRoute
  '/packages': typeof AuthPackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/authentication-sources': typeof AuthAuthenticationSourcesRoute
  '/_auth/deploy-tokens': typeof AuthDeployTokensRoute
  '/_auth/import-batches': typeof AuthImportBatchesRoute
  '/_auth/personal-tokens': typeof AuthPersonalTokensRoute
  '/_auth/repositories': typeof AuthRepositoriesRoute
  '/_auth/sources': typeof AuthSourcesRoute
  '/_auth/users': typeof AuthUsersRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/packages/$packageId': typeof AuthPackagesPackageIdRoute
  '/_auth/packages/': typeof AuthPackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/authentication-sources'
    | '/deploy-tokens'
    | '/import-batches'
    | '/personal-tokens'
    | '/repositories'
    | '/sources'
    | '/users'
    | '/'
    | '/packages/$packageId'
    | '/packages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/authentication-sources'
    | '/deploy-tokens'
    | '/import-batches'
    | '/personal-tokens'
    | '/repositories'
    | '/sources'
    | '/users'
    | '/'
    | '/packages/$packageId'
    | '/packages'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/authentication-sources'
    | '/_auth/deploy-tokens'
    | '/_auth/import-batches'
    | '/_auth/personal-tokens'
    | '/_auth/repositories'
    | '/_auth/sources'
    | '/_auth/users'
    | '/_auth/'
    | '/_auth/packages/$packageId'
    | '/_auth/packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sources': {
      id: '/_auth/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthSourcesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/repositories': {
      id: '/_auth/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof AuthRepositoriesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/personal-tokens': {
      id: '/_auth/personal-tokens'
      path: '/personal-tokens'
      fullPath: '/personal-tokens'
      preLoaderRoute: typeof AuthPersonalTokensRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/import-batches': {
      id: '/_auth/import-batches'
      path: '/import-batches'
      fullPath: '/import-batches'
      preLoaderRoute: typeof AuthImportBatchesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/deploy-tokens': {
      id: '/_auth/deploy-tokens'
      path: '/deploy-tokens'
      fullPath: '/deploy-tokens'
      preLoaderRoute: typeof AuthDeployTokensRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/authentication-sources': {
      id: '/_auth/authentication-sources'
      path: '/authentication-sources'
      fullPath: '/authentication-sources'
      preLoaderRoute: typeof AuthAuthenticationSourcesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/packages/': {
      id: '/_auth/packages/'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthPackagesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/packages/$packageId': {
      id: '/_auth/packages/$packageId'
      path: '/packages/$packageId'
      fullPath: '/packages/$packageId'
      preLoaderRoute: typeof AuthPackagesPackageIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuthenticationSourcesRoute: typeof AuthAuthenticationSourcesRoute
  AuthDeployTokensRoute: typeof AuthDeployTokensRoute
  AuthImportBatchesRoute: typeof AuthImportBatchesRoute
  AuthPersonalTokensRoute: typeof AuthPersonalTokensRoute
  AuthRepositoriesRoute: typeof AuthRepositoriesRoute
  AuthSourcesRoute: typeof AuthSourcesRoute
  AuthUsersRoute: typeof AuthUsersRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthPackagesPackageIdRoute: typeof AuthPackagesPackageIdRoute
  AuthPackagesIndexRoute: typeof AuthPackagesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthenticationSourcesRoute: AuthAuthenticationSourcesRoute,
  AuthDeployTokensRoute: AuthDeployTokensRoute,
  AuthImportBatchesRoute: AuthImportBatchesRoute,
  AuthPersonalTokensRoute: AuthPersonalTokensRoute,
  AuthRepositoriesRoute: AuthRepositoriesRoute,
  AuthSourcesRoute: AuthSourcesRoute,
  AuthUsersRoute: AuthUsersRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthPackagesPackageIdRoute: AuthPackagesPackageIdRoute,
  AuthPackagesIndexRoute: AuthPackagesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
